app:
  name: "go-crud-api"
  version: "user_test"
  environment: "local"

http:
  host: "0.0.0.0"
  port: 8080
  read_timeout: 5s
  write_timeout: 10s
  idle_timeout: 60s
  read_header_timeout: 5s

database:
  host: "localhost"
  port: 5432
  name: "go_crud"
  user: "postgres"
  password: "root"
  ssl: "disable"
  pool:
    min_cons: 1
    max_cons: 10
    max_con_life_time: 1h
    max_con_idle_time: 30m
    health_check_period: 1m

auth:
  jwt_secret: "local-dev-secret-change-me-please-32"
  access_token_ttl: 15m

redis:
  host: "localhost"
  port: 16379
  password: ""
  db: 0

cache:
  user_ttl: 5m

log:
  level: "info"