app:
  name: "go-crud-api"
  version: "test"
  environment: "local"

http:
  host: "0.0.0.0"
  port: 8080
  read_timeout: "5s"
  write_timeout: "10s"
  idle_timeout: "60s"

database:
  host: "localhost"
  port: 15432
  name: "go_crud"
  user: "go_crud"
  password: "go_crud"
  pool:
    min_cons: 1
    max_cons: 10
    max_con_life_time: 1h
    max_con_idle_time: 30m
    health_check_period: 1m

log:
  level: "info"