syntax = "proto3";

package api.user.v1;

import "google/protobuf/timestamp.proto";

option go_package = "github.com/300nn/go-identity-service/internal/gen/api/user/v1;userapiv1";

service UserService {
  rpc GetUser(GetUserRequest) returns (GetUserResponse);
  rpc ListUsers(ListUsersRequest) returns (ListUsersResponse);
}

message User {
  int64 id = 1;
  string name = 2;
  string email = 3;
  int32 age = 4;
  string role = 5;
  google.protobuf.Timestamp created_at = 6;
  google.protobuf.Timestamp updated_at = 7;
}

message GetUserRequest {
  int64 id = 1;
}

message GetUserResponse {
  User user = 1;
}

message ListUsersRequest {
  int32 limit = 1;
  int32 offset = 2;
  string email = 3;
  string sort = 4;
}

message ListUsersResponse {
  repeated User users = 1;
  int64 total = 2;
}
